device: "cuda" 

dataset:
  train_noisy: "data/train/noisy"
  train_clean: "data/train/clean"
  test_noisy: "data/test/noisy"

training:
  epochs: 200
  batch_size: 4
  learning_rate: 0.0001
  optimizer: adam
